theme: jekyll-theme-midnight
title: HODL Totals
description: For self-reliant crypto HODLers to remain in full compliance with tax laws and regulations.<br /><p><a href="https://dogracer.github.io/DCV-policy/Terms%20of%20Service/hodl-totals/EN-Terms-of-Service">Terms of Service</a></p><p><a href="https://dogracer.github.io/DCV-policy/Privacy-Policy">Privacy Policy</a></p><p><a href="https://dogracer.github.io/DCV-policy/Legal-Guidelines">Legal Guidelines</a></p>
logo: HODL-totals-card-banner.png
