theme: jekyll-theme-minimal
title: HODL Totals
description: For self-reliant crypto HODLers to remain in full compliance with tax laws and regulations. [Terms of Service](https://github.com/dogracer/DCV-policy/blob/master/Terms%20of%20Service/hodl-totals/EN-Terms-of-Service.md) [Privacy Policy](https://dogracer.github.io/DCV-policy/Privacy-Policy) [Legal Guidelines](https://dogracer.github.io/DCV-policy/Legal-Guidelines)
logo: HODL-totals-card-banner.png
