theme: jekyll-theme-minimal
title: HODL Totals
description: Use HODL Totals to become a self-reliant crypto HODLer in full compliance with tax laws and regulations, because anyone armed with the right information and training can truly unbank themselves and take control of their financial lives!
logo: logo128x128.png
